### ISSUE TITLE
Is it possible to set the path for WebDavMapping ambiguously?

### ISSUE THREAD

**Issue by achifal** [seanox/apiDAV#1]
Hey,
Judging by the documentation, the path for the `WebDavMapping` annotation cannot be set ambiguously.
It would be great to be able to specify a path of the format `path/{variable}/{name}.docx`, and then be able to get variable and name values with `@PathVariable`.
Is there any workaround to support such manipulations? Thanks in advance!

**Comment by seanox** [comment]
If I understand correctly, the wish is that for the example URL like `/path/{variable}/{name}.docx`, the value `/path` is static and the client can then dynamically define `variable` + `name` and then in the backend anything matching the pattern `/path/***/***.docx` is accepted.

This currently clashes with the concept of the sitemap as a navigable directory structure in WebDAV. In this case, the entries would not have a fixed path and could not be mapped that way.

I don't have a programmatic workaround ready off the top of my head. ___Just an untested idea.___ If there is a webserver with a rewrite engine in front of the backend, it can map a flexible pattern. The client could send what it wanted and the destination is an existing but hidden path in WebDav.  

```
RewriteEngine On
RewriteRule "^/path/([^/]+)/([^/]+)\.docx$" "/path/hidden.docx?value=$1;name=$2" [L]
```
or analyze the header directly without query parameters:
```
RewriteEngine On
RewriteRule "^/path/.*\.docx$" "/path/hidden.docx" [L]
```
or even more complicated the original path as header parameter:
```
RewriteEngine On
RewriteRule "^(/path/.*\.docx)$" "/path/hidden.docx" [L,E=REQUEST_PATH:$1]
Header Set Request-Path "%{REQUEST_PATH}"
```

**Comment by seanox** [comment]
Since there is no feedback, close the issue.
I assume that the solution works.

**Comment by juanmacintas** [comment]
Hi! Related with this, i have a question. If i have service that return a file path,  is it possible to define a path on a @WebDavMapping to return a file receive as parameter and use that service?
Thanks in advance

**Comment by seanox** [comment]
I am struggling to understand the question in relation to service. Is it a service in the context of Spring-Boot or a service in the sense of a REST API or other external component?

So I can only try to answer. The annotation @WebDavMapping is read at startup and sets up a mapping for paths that is immutable at runtime. All WebDav annotations support the Spring Expression Syntax. This means that an existing service can also create the path dynamically at startup.

**Comment by juanmacintas** [comment]
Thanks for your reply.

It's probably a problem I'm not understanding.

As I understand it, you define a WebDavMapping Controller with file access using a specific path.
What happens if I have a @Service that receives a parameter and queries a database where it obtains a file path to be returned?
How would the path be defined in the WebDavMapping for this case?

Thanks!

**Comment by seanox** [comment]
Annotations support Spring-Language-Expressions (SpEL). As these annotations are loaded when the Spring application is started, it should already be possible to access the service and use “dynamic” values. However, these values are also only loaded once at startup and are then unchangeable.
