### ISSUE TITLE
Spring 3: Controller Not Found

### ISSUE THREAD

**Issue by sankarinfo** [seanox/apiDAV#3]
using Spring Boot 3.4.1 with openJDK17

application.getBeanDefinitions() returns all classes including Controller’s in IntelliJ

Issue :

when build jar and deploy in RHEL linux open shift
application.getBeanDefinitions() returns all classes excluding Controller’s what could be the reason?

i can see FinancialServices and MarketingServices but cannot find FinancialController and MarketingController

**Comment by seanox** [comment]
The reason will be that the project was developed with Spring-Boot 2.x. I need to upgrade it to Spring-Boot 3.x.

I'll leave the issue open until I've done it. But I'm still on Devwex and this will take a few more days.

**Comment by seanox** [comment]
Perhaps the use of @RestController in FinancialController and MarketingController is also a misunderstanding. The Web-DAV implementation is for Spring-Boot and uses many of its approaches, but the exemplary controllers are not Spring-Boot controllers. Web-DAV works as a request filter and handles the request handling itself and works before the request processing of Spring-Boot-Web. But the Web-DAV implementation requires beans managed by Spring-Boot. These can be defined with various annotations. @RestController is one of them. You can also use @Service or similar, but @RestController looked good at the time :-)

see also here: https://github.com/seanox/spring-webdav/blob/main/src/test/java/com/seanox/api/financial/FinancialController.java#L42

**Comment by sankarinfo** [comment]
Thanks!  now it’s working using spring 2.7.2, currently document hardcoded /template/costs.xlsx, we want to make it dynamic ie like path variable so that we use different file, kindly advice

**Comment by seanox** [comment]
It is described in the sources and in the documentation that the handling of Office documents is not part of WebDAV. As a simple example, as already mentioned, a static file is used as a template. In practice, the generation should be programmatic and therefore dynamic as desired. Apache POI can be used for this purpose. In relation to the example contained in WebDAV, FinancialController.financialCostsGet(...) would be the method where the Excel file is created and FinancialController.financialCostsPut(...) the method where the upload is received. This would then have to be changed to POI.

**Comment by sankarinfo** [comment]
Thanks, tried change get method, but opening excel read only mode, can u provide some sample

**Comment by seanox** [comment]
I can reproduce it with Office 365. But I won't have time to look at it in detail for about 2 weeks.

**Comment by sankarinfo** [comment]
excel document is protected by default, so after opening document it’s pops up status message “Enable Editing ………” if we click on that status, its reload page again and throws exception version issue, work around need to disable protected view in client side word/excel desktop app

**Comment by seanox** [comment]
About  "Enable Editing"
This is MS Office standard behavior when opening files from unknown sources. Network drives, as well as WebDAV, are included here. The solution should be to explain to Office that the source is trustworthy -- please have a look here: 
https://www.process.st/how-to/turn-off-enable-editing-in-microsoft-office-2016/#:~:text=Go%20to%20the%20'Trust%20Center,boxes%20under%20Protected%20View%20settings.

**Comment by seanox** [comment]
In the upcoming version 1.2.x, some errors have been corrected to improve the use of Office 365. For example, the permanent and incorrect indication that the file has been changed in the meantime has been corrected. OpenOffice is also being tested more actively. For Spring 3.x there will be the next version 1.3.x.

**Comment by seanox** [comment]
Controller Not Found - with Spring 3 is solved in version 1.3.0. The release will follow in the next few days.
Reason and solution: New name of the javax JEE packages, which are now called jakarta.
https://www.baeldung.com/spring-boot-3-spring-6-new
